[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "SCIERA Documentation"
authors = [{name = "Ovgu Magdeburg, ETH Zurich", email = "marten.gartner@ovgu.de"}]
dynamic = ["version", "description"]
